<a href="https://colab.research.google.com/github/Akhilesh1118/Python/blob/main/Lecture%208/Chapter_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Learning Objectives

After completing this notebook, you will be able to:

- Identify missing values
- Handle duplicates
- Convert data types
- Clean string data
- Transform columns
- Sort and rank data

# Data Cleaning
• Handle Missing Values ( `NaN`)
1. `isnull()/isna()` -  Shows boolean DataFrame, True where NaN
2. `isnull().sum()` - Count of NaNs per column
3. `dropna()` -  Drop rows with any NaN
4. `fillna(value)` -  Fills NaN with a value
5. `ffill()` -  Forward Fill (carry previous value)
6. `bfill()` -  Backward Fill (carry next value)

In [3]:
import pandas as pd

In [7]:
df = pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [ ]:
# True for null values (NaN)
df.isnull()

df.isna()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [8]:
df.isnull().sum()    # counts missing vals per column

df.dropna()          # drops rows with missing values

df.dropna(axis = 1)  #  drops columns with missing values

df.fillna(0)       # fills NaN with 0

age_mean = df["age"].mean()  # fills column with mean
df["age"].fillna(age_mean)

0     29.00
1     29.00
2     32.75
3     32.75
4     34.00
5     27.00
6     45.00
7     38.00
8     29.00
9     32.75
10    31.00
Name: age, dtype: float64

In [9]:
cleaned_data = df.copy()
age_mean = cleaned_data["age"].mean()
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean)

cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [10]:
df.fillna(method = "ffill") # forward fill
df.fillna(method = "bfill") # backward fill

/tmp/ipykernel_3047/1844656732.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill") # forward fill
/tmp/ipykernel_3047/1844656732.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "bfill") # backward fill

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

# Handle Duplicates ( )

1. `df.duplicated()` - Find duplicates
2. `df.drop_duplicates()` - Remove duplicate rows

In [11]:

df.duplicated()              # True for duplicate rows
df.duplicated("country")     # True for duplicate rows in particular col
df[["country", "gender"]].duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [12]:
df2 = df.copy()

df.drop_duplicates(inplace=True) # drops duplicate rows
df2

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

# Handling Data Types & date-time

1. `df.astype(new_type)` - Change dtypes.
2. `pd.to_datetime()` - To convert a string, number, or array-like object to a datetime object.

In [14]:
df.dtypes

id           int64
name        object
age        float64
country     object
gender      object
income     float64
dtype: object

In [15]:
df.dtypes

df2 = df.copy()
df2 = df2.fillna(0)

df2["age"] = df2["age"].astype("int64").copy() #  change dtype
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [16]:
df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  Canada   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      0.0
5    5        Li Wei   27   China     Male  51000.0
6    6             0   45   India   Female  73000.0
7    7    Ahmed Khan   38       0     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  Mexico     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0

In [19]:
aqi_data = pd.read_csv("globalAirQuality.csv")
aqi_data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [23]:
aqi_data.dtypes # Print all the columns types

timestamp       object
country         object
city            object
latitude       float64
longitude      float64
pm25           float64
pm10           float64
no2            float64
so2            float64
o3             float64
co             float64
aqi              int64
temperature    float64
humidity       float64
wind_speed     float64
dtype: object

In [20]:
# It represent acutal data type of date formate
date_str = pd.Series([pd.to_datetime("2026-11-21")])
print(date_str.dtypes)

datetime64[ns]

In [28]:
print(aqi_data["timestamp"].dtypes) # In the give table timestamp in Object datatypes change in to Date type .

object

In [30]:
aqi_data["timestamp"] = pd.to_datetime(aqi_data["timestamp"]) # Change the Object dtypes into Date dtypes.
aqi_data.dtypes # Verify the column types.

timestamp      datetime64[ns]
country                object
city                   object
latitude              float64
longitude             float64
pm25                  float64
pm10                  float64
no2                   float64
so2                   float64
o3                    float64
co                    float64
aqi                     int64
temperature           float64
humidity              float64
wind_speed            float64
dtype: object

#String Cleaning
1. `.str.lower()` - Convert to lowercase
2. `.str.upper()` - Convert to uppercase
3. `.str.capitalize()` - Capitalize strings
4. `.str.strip()` -  Remove leading/trailing spaces
5. `.str.contains()` - Check if a value exists in string or not
6. `.str.split(" ")` -  Split into parts based on a separato

In [31]:
df['gender'].str.lower()      # lower case
df['gender'].str.upper()      # upper case
df['gender'].str.capitalize() # capitalize

0        Male
2      Female
3     Unknown
4      Female
5        Male
6      Female
7        Male
8      Female
9        Male
10        NaN
Name: gender, dtype: object

In [ ]:
df2["name"].str.split(" ")    # splits into lists
type(df2["name"].str.split(" ")[0])

list

In [36]:
# Returns True for rows where 'country' has "US", False otherwise
df2["country"].str.contains("US")

# case=False makes the search ignore uppercase/lowercase differences
df2["country"].str.contains("india", case=False)

0     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

---

# Transforming Data
- `apply()`
- `map()`
- `assign()`
- `replace(old,new)`
- `rename(columns={old:new})`
- `sort_values()`
- `sort_index()`
- `reset_index()`
- `rank()`
- `Reorder columns`

1. `apply()` -  Apply a function to a Series or DataFrame.

In [37]:
df2 = df.copy()

df2['tax'] = df2['income'].apply(lambda x : "20%" if x >= 60000 else "10%")
df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  10%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  10%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  10%

2. `map()`-  Map a function or dictionary to a Series

In [38]:
gender_map = {
    "Male" : "M",
    "Female" : "F",
    "Unknown" : "U"
}

df2["gender"] = df2["gender"].map(gender_map)
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  10%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  10%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%

In [39]:
# Orginal data set.
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

3. `assign()` - Create new columns or modify existing columns.

In [55]:
df2 = df2.assign(new_income = df2["income"]   * 1.1) # increase the value of 10 % every income
df2

    id          name   age        country gender   income  tax  new_income
0    1      John Doe  29.0  United States      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN         Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN  United States      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0          Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0          China      M  51000.0  10%     56100.0
6    6           NaN  45.0          India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0            NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United States      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN         Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United States    NaN  58000.0  10%     63800.0

4. `replace(old, new)`- Replace specific values in a Series or DataFrame.

In [56]:
df2["country"] = df2["country"].replace("USA", "United States") # Change the name
df2

    id          name   age        country gender   income  tax  new_income
0    1      John Doe  29.0  United States      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN         Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN  United States      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0          Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0          China      M  51000.0  10%     56100.0
6    6           NaN  45.0          India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0            NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United States      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN         Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United States    NaN  58000.0  10%     63800.0

# Renaming / Reordering

1. `rename()`

In [73]:
df2

    Id          Name   Age        Country Gender   Income  Tax  New_Income
0    1      John Doe  29.0  United States      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN         Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN  United States      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0          Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0          China      M  51000.0  10%     56100.0
6    6           NaN  45.0          India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0            NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United States      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN         Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United States    NaN  58000.0  10%     63800.0

In [72]:
df3 = df2.rename(columns={"Income":"Salary"})  # Change the name of Income in to Salary store
df3

    Id          Name   Age        Country Gender   Salary  Tax  New_Income
0    1      John Doe  29.0  United States      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN         Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN  United States      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0          Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0          China      M  51000.0  10%     56100.0
6    6           NaN  45.0          India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0            NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United States      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN         Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United States    NaN  58000.0  10%     63800.0

In [42]:
df3 = pd.DataFrame({
"A": [1, 2, 3],
"B": [4, 5, 6],
"C": [7, 8, 9]
})
# Rename columns A -> X, B -> Y
df_renamed = df3.rename(columns={"A": "X", "B": "Y"})
print(df_renamed)

   X  Y  C
0  1  4  7
1  2  5  8
2  3  6  9

2. Reorder Columns  
The list must include all columns we want to keep & columns not listed will be
dropped.

In [43]:
df3.columns = ["X", "Y", "C"]  # reorders all at once

# Reorder columns to C, A, B
df_reordered = df3[["C", "X", "Y"]]
df3

   X  Y  C
0  1  4  7
1  2  5  8
2  3  6  9

3. Reset Index

In [44]:
df3.reset_index()
df3.reset_index(drop=True)  # to drop original index vals

   X  Y  C
0  1  4  7
1  2  5  8
2  3  6  9

---

In [57]:
df2.columns

Index(['id', 'name', 'age', 'country', 'gender', 'income', 'tax',
       'new_income'],
      dtype='object')

In [70]:
df2.columns = ["Id" , "Name" ,"Age" , "Country","Gender","Income","Tax","New_Income" ]
df2.rename(index={3:"three"})  # replace the 3 index with three

       Id          Name   Age        Country Gender   Income  Tax  New_Income
0       1      John Doe  29.0  United States      M  55000.0  10%     60500.0
2       2    Jane Smith   NaN         Canada      F  62000.0  20%     68200.0
three   3          Alex   NaN  United States      U  47000.0  10%     51700.0
4       4  Maria Garcia  34.0          Spain      F      NaN  10%         NaN
5       5        Li Wei  27.0          China      M  51000.0  10%     56100.0
6       6           NaN  45.0          India      F  73000.0  20%     80300.0
7       7    Ahmed Khan  38.0            NaN      M  68000.0  20%     74800.0
8       8    Rachel Lee  29.0  United States      F  62000.0  20%     68200.0
9       9   Carlos Ruiz   NaN         Mexico      M  45000.0  10%     49500.0
10     10   Emily Davis  31.0  United States    NaN  58000.0  10%     63800.0

# Sorting / Ranking
1. `sort_values()`- Sort values in ascending or descending order.
2. `sort_index()` -  Sort indexes in ascending or descending order.
3. `rank()` - Sort values in ascending or descending order, `method` resolves the ties.

In [ ]:
# Sorting - values & index
df2 = df2.fillna(50)
df2.sort_values("Income")                   # sort values in ascending
df2.sort_values("Income", ascending=False)  # sort values in descending
df2.sort_values(["Income", "Age"])          # sorts age,if age same then sorts income

sorted_df = df2.sort_values(["Income", "Age"])
sorted_df

       Id          Name   Age        Country Gender   Income  Tax  New_Income
4       4  Maria Garcia  34.0          Spain      F     50.0  10%        50.0
9       9   Carlos Ruiz  50.0         Mexico      M  45000.0  10%     49500.0
three   3          Alex  50.0  United States      U  47000.0  10%     51700.0
5       5        Li Wei  27.0          China      M  51000.0  10%     56100.0
0       1      John Doe  29.0  United States      M  55000.0  10%     60500.0
10     10   Emily Davis  31.0  United States     50  58000.0  10%     63800.0
8       8    Rachel Lee  29.0  United States      F  62000.0  20%     68200.0
2       2    Jane Smith  50.0         Canada      F  62000.0  20%     68200.0
7       7    Ahmed Khan  38.0             50      M  68000.0  20%     74800.0
6       6            50  45.0          India      F  73000.0  20%     80300.0

In [ ]:
sorted_df.sort_index()

# reset
sorted_df.reset_index()
sorted_df.reset_index(drop=True)

   Id          Name   Age Country Gender   Income  Tax  New_Income
0   4  Maria Garcia  34.0   Spain      F     50.0  10%        50.0
1   9   Carlos Ruiz  50.0  Mexico      M  45000.0  10%     49500.0
2   3          Alex  50.0      US      U  47000.0  10%     51700.0
3   5        Li Wei  27.0   China      M  51000.0  10%     56100.0
4   1      John Doe  29.0      US      M  55000.0  10%     60500.0
5  10   Emily Davis  31.0      US     50  58000.0  10%     63800.0
6   8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
7   2    Jane Smith  50.0  Canada      F  62000.0  20%     68200.0
8   7    Ahmed Khan  38.0      50      M  68000.0  20%     74800.0
9   6            50  45.0   India      F  73000.0  20%     80300.0

In [ ]:
# Replace the position of tax column
sorted_df[["Id" , "Name" ,"Age" , "Country","Gender","Income","New_Income","Tax" ]]

    Id          Name   Age Country Gender   Income  New_Income  Tax
4    4  Maria Garcia  34.0   Spain      F     50.0        50.0  10%
9    9   Carlos Ruiz  50.0  Mexico      M  45000.0     49500.0  10%
3    3          Alex  50.0      US      U  47000.0     51700.0  10%
5    5        Li Wei  27.0   China      M  51000.0     56100.0  10%
0    1      John Doe  29.0      US      M  55000.0     60500.0  10%
10  10   Emily Davis  31.0      US     50  58000.0     63800.0  10%
8    8    Rachel Lee  29.0      US      F  62000.0     68200.0  20%
2    2    Jane Smith  50.0  Canada      F  62000.0     68200.0  20%
7    7    Ahmed Khan  38.0      50      M  68000.0     74800.0  20%
6    6            50  45.0   India      F  73000.0     80300.0  20%

In [ ]:
# Ranking
sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False, method="dense")
sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False, method="min")
sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False, method="max")
sorted_df

,Id,Name,Age,Country,Gender,Income,Tax,New_Income,Ranking
4,4,Maria Garcia,34.0,Spain,F,50.0,10%,50.0,10.0
9,9,Carlos Ruiz,50.0,Mexico,M,45000.0,10%,49500.0,9.0
three,3,Alex,50.0,United States,U,47000.0,10%,51700.0,8.0
5,5,Li Wei,27.0,China,M,51000.0,10%,56100.0,7.0
0,1,John Doe,29.0,United States,M,55000.0,10%,60500.0,6.0
10,10,Emily Davis,31.0,United States,50,58000.0,10%,63800.0,5.0
8,8,Rachel Lee,29.0,United States,F,62000.0,20%,68200.0,4.0
2,2,Jane Smith,50.0,Canada,F,62000.0,20%,68200.0,4.0
7,7,Ahmed Khan,38.0,50,M,68000.0,20%,74800.0,2.0
6,6,50,45.0,India,F,73000.0,20%,80300.0,1.0

---
## Key Takeaways

- Missing values can be identified using isnull().
- fillna() helps replace missing values.
- duplicated() identifies duplicate records.
- astype() changes data types.
- apply() and map() transform data efficiently.
- sort_values() and rank() help organize data.